baseURL       = "https://aish-where-ya.github.io"
languageCode  = "en-us"
title         = "Aishwarya Harpale | Portfolio"
theme         = "roxo"
summarylength = 25

# Site Menus
[menu]
  # Navbar Menus
  [[menu.nav]]
    name    = "Home"
    url     = ""
    weight  = 1
  [[menu.nav]]
    name    = "About"
    url     = "about"
    weight  = 2
  [[menu.nav]]
    name    = "Portfolio"
    url     = "portfolio"
    weight  = 3
  [[menu.nav]]
    name    = "Contact"
    url     = "contact"
    weight  = 4
  [[menu.nav]]
    name    = "Download Resume"
    url     = "files/Aishwarya_Harpale_Resume_Apr21.pdf"
    weight  = 5

# Site Params
[params]
  logo = "images/logo.png"
  dateFormat = "26 FEB 1994"
  # Meta data
  description = "Roxo Hugo themes | Design Agency Template by StaticMania"
  author = "StaticMania"
  # Google Analitycs
  googleAnalitycsID = "Your ID"
  # We're using formspree.io for form handling, paste your formspree url below
  formspreeFormUrl  = "https://formspree.io/f/mzbyzvle"
  
  # Navbar Action Button
  [params.navAction]
    status  = true
    name    = "Get in touch"
    url     = "contact"
  

  # Banner Section
  [params.banner]
    enable                = true
    background_image      = "images/backgrounds/hero-background.jpg"
    heading               = "Hello, I'm Aishwarya Harpale. And I code!"
    tagline               = "WELCOME TO MY PAGE"
    primary_button        = "See My Work"
    primary_button_url    = "portfolio"
    secondary_button      = "Get In Touch"
    secondary_button_url  = "contact"

  [params.portfolio]
    enable    = true
    title     = "MY RECENT WORKS"
    subtitle  = "Experimenting with tech and solving complex problems."

  [params.call_to_action]
    enable              = true
    background_image    = "images/backgrounds/cta-background.jpg"
    title               = "LET’S WORK TOGETHER"
    primary_button      = "Submit Query"
    primary_button_url  = "contact"
    secondary_button    = "Not Convinced"
    secondary_button_url = "portfolio"

  [params.footer]
    # Footer Contact Info
    [params.footer.contactInfo]
      # Footer Sitemap
      [params.footer.sitemap]
        title   = "Sitemap"
        [[params.footer.sitemap.link]]
          name = "About"
          url  = "about"
        [[params.footer.sitemap.link]]
          name = "Portfolio"
          url  = "portfolio"
        [[params.footer.sitemap.link]]
          name = "Contact"
          url  = "contact"
      # Footer Social Media
      [params.footer.social]
        title   = "Social Media"
        [[params.footer.social.link]]
          name = "Github"
          url  = "https://github.com/aish-where-ya"
        [[params.footer.social.link]]
          name = "LinkedIn"
          url  = "https://www.linkedin.com/in/aishwaryaharpale/"
        [[params.footer.social.link]]
          name = "GitLab"
          url  = "https://gitlab.com/aish-where-ya"
        [[params.footer.social.link]]
          name = "Instagram"
          url  = "https://www.instagram.com/aish_where_ya/"
      # Footer Service
      [params.footer.service]
        title       = "I help organizations:"
        description = "develop design solutions<br>produce quick valuable outcomes<br>bring fresh experiences to the table"